import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MoviesProvider } from "@/components/MoviesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kino v topku",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MoviesProvider>{children}</MoviesProvider>
      </body>
    </html>
  );
}
